=== asjadathick/CSCI235/lab8/task3-3.dtd
<!ELEMENT department (name, chairman, budget, buildings, has-employees)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT chairman (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT buildings (building+)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT has-employees (employee+)>
<!ELEMENT employee (enum, first-name, last-name, salary)>
<!ELEMENT enum (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== asjadathick/CSCI235/lab8/task3-3.xml
<?xml version="1.0"?>
<!DOCTYPE department SYSTEM "task3-3.dtd">
<department>
  <name>sales</name>
  <chairman>John Doe</chairman>
  <budget>10K</budget>
  <buildings>
    <building>3</building>
    <building>39</building>
    <building>150</building>
  </buildings>
  <has-employees>
    <employee>
      <enum>1234</enum>
      <first-name>John</first-name>
      <last-name>Doe</last-name>
      <salary>100K</salary>
    </employee>
    <employee>
      <enum>1235</enum>
      <first-name>Henry</first-name>
      <last-name>Eight</last-name>
      <salary>30K</salary>
    </employee>
    <employee>
      <enum>1236</enum>
      <first-name>Jack</first-name>
      <last-name>Long</last-name>
      <salary>50K</salary>
    </employee>
  </has-employees>
</department>
