=== asjadathick/CSCI235/lab8/task3-4.dtd
<!ELEMENT expression ((number, operation, number) | (left-bracket, expression, right-bracket, operation, number))>
<!ELEMENT number (#PCDATA)>
<!ELEMENT operation (#PCDATA)>
<!ELEMENT left-bracket (#PCDATA)>
<!ELEMENT right-bracket (building+)>

=== asjadathick/CSCI235/lab8/task3-4.xml
<?xml version="1.0"?>
<!DOCTYPE expression SYSTEM "task3-4.dtd">
<expression>
  <left-bracket>(</left-bracket>
  <expression>
    <left-bracket>(</left-bracket>
    <expression>
      <number>24</number>
      <operation>+</operation>
      <number>24</number>
    </expression>
    <right-bracket>)</right-bracket>
    <operation>*</operation>
    <number>5</number>
  </expression>
  <right-bracket>)</right-bracket>
  <operation>-</operation>
  <number>6</number>
</expression>
