=== asjadathick/CSCI235/lab8/task3-2.dtd
<!ELEMENT book (isbn, title, author+, chapters, publisher, keywords)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (last-name, initials)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT initials (#PCDATA)>
<!ELEMENT chapters (chapter+)>
<!ELEMENT chapter (number, title)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT keywords (keyword+)>
<!ELEMENT keyword (#PCDATA)>

=== asjadathick/CSCI235/lab8/task3-2.xml
<?xml version="1.0"?>
<!DOCTYPE book SYSTEM "task3-2.dtd">
<book>
  <isbn>007</isbn>
  <title>Database Performance Tuning</title>
  <author>
    <last-name>Millsap</last-name>
    <initials>C</initials>
  </author>
  <author>
    <last-name>Burleson</last-name>
    <initials>D</initials>
  </author>
  <chapters>
    <chapter>
      <number>1</number>
      <title>Introduction</title>
    </chapter>
    <chapter>
      <number>2</number>
      <title>Tuning Database Server</title>
    </chapter>
    <chapter>
      <number>3</number>
      <title>Tuning Query Processing</title>
    </chapter>
    <chapter>
      <number>4</number>
      <title>Tuning Data Manipulations</title>
    </chapter>
  </chapters>
  <publisher>Oracle Press</publisher>
  <keywords>
    <keyword>database</keyword>
    <keyword>performance</keyword>
  </keywords>
</book>
