=== asjadathick/CSCI235/ass3/task5.dtd
<!ELEMENT multicompany (natdivision+)>
<!ELEMENT natdivision (country, address, branch+)>
<!ELEMENT address (city, street, building, phone?, fax?)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT fax (#PCDATA)>
<!ELEMENT branch (address, name, department+)>
<!ELEMENT name (fistname, initials, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT initials (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT department (departmentname, name, budget, employee*)>
<!ELEMENT departmentname (#PCDATA)>
<!ELEMENT budget (#PCDATA)>
<!ELEMENT employee (name, position)>
<!ELEMENT position (#PCDATA)>

=== asjadathick/CSCI235/ass3/task5.xml
<?xml version="1.0"?>
<!DOCTYPE multicompany SYSTEM "task5.dtd">
<multicompany>
	<natdivision>
		<country>Australia</country>
		<address>
			<city>Sydney</city>
			<street>One Loop</street>
			<building>1</building>
			<phone>12345</phone>
			<fax>122323</fax>
		</address>
		<branch>
			<address>
				<city>Sydney</city>
				<street>One Loop</street>
				<building>1</building>
				<phone>12345</phone>
				<fax>122323</fax>
			</address>
			<name>
				<firstname>Asjad</firstname>
				<initials>MA</initials>
				<lastname>Athick</lastname>
			</name>
			<department>
				<departmentname>IT</departmentname>
				<name>
					<firstname>Asjad</firstname>
					<initials>MA</initials>
					<lastname>Athick</lastname>
				</name>
				<employee>
					<name>
						<firstname>Asjad</firstname>
						<initials>MA</initials>
						<lastname>Athick</lastname>
					</name>
				</employee>
			</department>
		</branch>
	</natdivision>
</multicompany>
